language: node_js

node_js:
  - "node"

services: mongodb

install:
  - npm install

script:
  - npm test
  - npm run test:all
  - npm run check-coverage
after_success:
  - npm run report-coverage

env:
- NODE_ENV=test

